capricorn86/happy-dom

src/nodes/basic-types/element/Element.ts
test/element/Element.test.ts
test/html-parser/HTMLParser.test.ts

I was missing `hasAttribute` method :)

Add support for hasAttribute method

---

packages/happy-dom/src/nodes/svg-element/ISVGElement.ts
packages/happy-dom/src/nodes/svg-element/SVGElement.ts
packages/happy-dom/test/nodes/document/Document.test.ts
packages/happy-dom/test/nodes/svg-element/SVGSVGElement.test.ts

To address https://github.com/capricorn86/happy-dom/issues/319
Similar implementation to `HTMLElement.ts`.

adding style property to SVGElement

---

packages/global-registrator/src/GlobalRegistrator.ts
packages/global-registrator/test/react/React.test.tsx

Also fixes some bad grammar in the errors and includes `unregister` in the test

#509@patch: Fix GlobalRegistrator's unregister.

---

docs/contributing.md

I noticed a typo in `contribute.md`

#0@trivial: Fix typo in contribute.md.

---

packages/happy-dom/src/fetch/Response.ts
packages/happy-dom/test/fetch/Response.test.ts

Fixes https://github.com/capricorn86/happy-dom/issues/542

#542@patch: Fix Response constructor issue.

---

packages/happy-dom/src/file/Blob.ts
packages/happy-dom/test/file/Blob.test.ts

https://developer.mozilla.org/en-US/docs/Web/API/Blob/arrayBuffer

add blob arrayBuffer()

---

package-lock.json
packages/happy-dom/src/nodes/html-select-element/HTMLSelectElement.ts

#548@patch: Fix incorrect logic in selectEl.selectedIndex setter.

---

packages/happy-dom/src/query-selector/QuerySelector.ts
packages/happy-dom/test/nodes/element/Element.test.ts

#614@patch: Element.matches not working properly with descendant combinators.

---

packages/happy-dom/src/config/ElementTag.ts
packages/happy-dom/src/dom-token-list/DOMTokenList.ts
packages/happy-dom/src/nodes/element/Element.ts
packages/happy-dom/src/nodes/html-anchor-element/HTMLAnchorElement.ts
packages/happy-dom/src/nodes/html-anchor-element/HTMLAnchorElementUtility.ts
packages/happy-dom/src/nodes/html-anchor-element/IHTMLAnchorElement.ts
packages/happy-dom/src/nodes/html-anchor-element/IHTMLHyperlinkElementUtils.ts
packages/happy-dom/src/nodes/html-link-element/HTMLLinkElement.ts
packages/happy-dom/test/nodes/html-anchor-element/HTMLAnchorElement.test.ts

#204@minor: Add support for HTMLAnchorElement.

---

package-lock.json
packages/happy-dom/src/query-selector/SelectorItem.ts
packages/happy-dom/test/nodes/element/Element.test.ts
packages/happy-dom/test/query-selector/QuerySelector.test.ts

This is definitely not the best way of doing this but it does seem to fix the issue #661. This is more of a proof of concept or pathfinder for how to fix the issue properly. See the issue for more details.

#661@patch: Take class selector escaping into account.

---

packages/happy-dom/src/event/events/CustomEvent.ts

#701@patch: fix handling of falsy CustomEvent detail value

---

packages/happy-dom/src/window/IWindow.ts
packages/happy-dom/src/window/Window.ts
packages/happy-dom/test/window/Window.test.ts

#712@patch: fix handling of callback arguments passing given to setTimeout / setInterval

---

packages/happy-dom/src/query-selector/SelectorItem.ts
packages/happy-dom/test/query-selector/QuerySelector.test.ts
packages/happy-dom/test/query-selector/data/QuerySelectorHTML.ts

#715@patch: Attribute value can contains point.

---

packages/happy-dom/src/nodes/element/Element.ts
packages/happy-dom/src/nodes/element/IElement.ts
packages/happy-dom/test/nodes/element/Element.test.ts

#724@minor: Add toggleAttribute.

---

packages/happy-dom/package.json

rel https://github.com/kulshekhar/ts-jest/pull/3780

#0@trivial: Update ts-jest config remove warn.

---

packages/happy-dom/src/query-selector/SelectorItem.ts
packages/happy-dom/test/query-selector/QuerySelector.test.ts

#753@patch: Pseudo `not` should match element

---

packages/happy-dom/src/config/PlainTextElements.ts
packages/happy-dom/src/xml-parser/XMLParser.ts
packages/happy-dom/test/dom-parser/DOMParser.test.ts

Solves #759, added test case in `DOMParser.test.ts`.

#759@patch: Spurious HTML comments in embedded scripts.

---

packages/happy-dom/src/window/Window.ts

#761@minor: Window add SVGGraphicsElement.

---

packages/happy-dom/src/nodes/node/Node.ts

#776@patch: Add self equality check in node.contains method.

---

packages/happy-dom/src/event/events/ISubmitEventInit.ts
packages/happy-dom/src/event/events/SubmitEvent.ts
packages/happy-dom/src/index.ts
packages/happy-dom/src/nodes/html-form-element/HTMLFormElement.ts
packages/happy-dom/src/window/IWindow.ts
packages/happy-dom/src/window/Window.ts
packages/happy-dom/test/event/events/SubmitEvent.test.ts
packages/happy-dom/test/nodes/html-form-element/HTMLFormElement.test.ts

fix #820
- add class `SubmitEvent`
- `HTMLFormElement.requestSubmit` triggers a `SubmitEvent`
- adapted unit tests

#820@minor: Add SubmitEvent.

---

packages/happy-dom/src/nodes/node/INode.ts
packages/happy-dom/src/nodes/node/Node.ts
packages/happy-dom/src/nodes/node/NodeUtility.ts
packages/happy-dom/src/range/Range.ts
packages/happy-dom/test/nodes/node/Node.test.ts
packages/happy-dom/test/nodes/node/NodeUtility.test.ts

fix #300
- Add method `Node.normalize`
- Add helper `NodeUtility.isTextNode` with type assertion
- Add unit tests for `Node.normalize` and `NodeUtility.isTextNode`
- Fix typo in `NodeUtility.nextDescendantNode` method name

#300@minor: Add Node.normalize()

---

packages/happy-dom/src/nodes/character-data/CharacterDataUtility.ts
packages/happy-dom/test/nodes/element/Element.test.ts

#870@patch: Convert HTML entities should include  semicolon.

---

packages/happy-dom/src/fetch/Request.ts
packages/happy-dom/src/fetch/types/IRequest.ts
packages/happy-dom/test/fetch/Request.test.ts

#892@patch: Implement `Request.formData()`.

---

packages/happy-dom/src/css/declaration/utilities/CSSStyleDeclarationElementStyle.ts

#889@patch: Fix parseCSSRules parsing keyframe error.

---

packages/happy-dom/src/nodes/document/Document.ts
packages/happy-dom/src/nodes/document/IDocument.ts
packages/happy-dom/test/nodes/document/Document.test.ts

#896@minor: Add document.links.

---

packages/happy-dom/src/fetch/Request.ts
packages/happy-dom/test/fetch/Request.test.ts

- Add Content-Type header while constructing Request
- Add tests

#1016@minor: Add Content-Type header for Request.

---

packages/happy-dom/src/nodes/html-dialog-element/HTMLDialogElement.ts
packages/happy-dom/test/nodes/html-dialog-element/HTMLDialogElement.test.ts

See issue: https://github.com/capricorn86/happy-dom/issues/1064

#1064@patch: Emit close event only when dialog was open.

---

packages/happy-dom/src/nodes/html-element/HTMLElement.ts
packages/happy-dom/src/nodes/html-element/IHTMLElement.ts
packages/happy-dom/test/nodes/html-element/HTMLElement.test.ts

#1089@minor: Add clientLeft and clientTop.

---

packages/happy-dom/src/event/Event.ts
packages/happy-dom/src/event/UIEvent.ts
packages/happy-dom/src/event/events/AnimationEvent.ts
packages/happy-dom/src/event/events/CustomEvent.ts
packages/happy-dom/src/event/events/ErrorEvent.ts
packages/happy-dom/src/event/events/FocusEvent.ts
packages/happy-dom/src/event/events/IPointerEventInit.ts
packages/happy-dom/src/event/events/IStorageEventInit.ts
packages/happy-dom/src/event/events/InputEvent.ts
packages/happy-dom/src/event/events/KeyboardEvent.ts
packages/happy-dom/src/event/events/MediaQueryListEvent.ts
packages/happy-dom/src/event/events/MessageEvent.ts
packages/happy-dom/src/event/events/MouseEvent.ts
packages/happy-dom/src/event/events/PointerEvent.ts
packages/happy-dom/src/event/events/ProgressEvent.ts
packages/happy-dom/src/event/events/StorageEvent.ts
packages/happy-dom/src/event/events/SubmitEvent.ts
packages/happy-dom/src/event/events/WheelEvent.ts
packages/happy-dom/test/nodes/html-element/HTMLElement.test.ts

Specification: https://w3c.github.io/pointerevents/#dom-pointerevent-constructor
Fix #1092

#1092@patch: Makes PointerEvent implementation more specification compliant.

---

packages/happy-dom/src/form-data/FormData.ts
packages/happy-dom/test/form-data/FormData.test.ts
packages/happy-dom/test/window/Window.test.ts

A fix for https://github.com/capricorn86/happy-dom/issues/1136

#1136@patch: Fix FormData.forEach callback parameters order.

---

packages/happy-dom/src/nodes/html-element/HTMLElement.ts
packages/happy-dom/test/nodes/html-element/HTMLElement.test.ts

Close #1124 
https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/inert

feat: [#1124] Implement inert attribute

---

packages/happy-dom/src/config/HTMLElementConfig.ts
packages/happy-dom/src/config/IHTMLElementTagNameMap.ts
packages/happy-dom/src/index.ts
packages/happy-dom/src/nodes/html-time-element/HTMLTimeElement.ts
packages/happy-dom/src/window/BrowserWindow.ts
packages/happy-dom/test/nodes/html-time-element/HTMLTimeElement.test.ts

Implements the `HTMLTimeElement` type. Closes #1431 
Please let me know if I’ve missed anything here

feat: [#1431] Implement HTMLTimeElement

---

packages/happy-dom/src/cookie/CookieContainer.ts

Fixes https://github.com/capricorn86/happy-dom/issues/1455

fix: [#1455] Cookie container cache key

---

packages/happy-dom/src/nodes/html-input-element/HTMLInputElement.ts
packages/happy-dom/src/nodes/html-text-area-element/HTMLTextAreaElement.ts
packages/happy-dom/test/browser/BrowserFrame.test.ts
packages/happy-dom/test/nodes/html-input-element/HTMLInputElement.test.ts
packages/happy-dom/test/nodes/html-text-area-element/HTMLTextAreaElement.test.ts

…MLInputElement and HTMLTextAreaElement

fix: [#1487] Changes wrong property name inputmode to inputMode in HTMLInputElement and HTMLTextAreaElement

---

.gitignore
.vscode/extensions.json
vitest.workspace.ts

Convenient and quick execution of debugging test cases.

chore: [1523] Add vitest extensions

---

packages/happy-dom/src/mutation-observer/MutationObserver.ts
packages/happy-dom/src/window/BrowserWindow.ts

…after disconnecting in MutationObserver

fix: [#1527] Fixes problem where it is not possible to observe again after disconnecting in MutationObserver

---

package-lock.json
packages/happy-dom/package.json

The current vitest version does not match the @vitest/ui version

chore: [husky] Update vite

---

packages/happy-dom/src/window/BrowserWindow.ts
packages/happy-dom/test/window/BrowserWindow.test.ts

Fixes https://github.com/capricorn86/happy-dom/issues/1611

fix: [#1611] Implement window.TextEncoder & window.TextDecoder

---

packages/happy-dom/src/fetch/multipart/MultipartFormDataParser.ts
packages/happy-dom/src/fetch/multipart/MultipartReader.ts
packages/happy-dom/test/fetch/Fetch.test.ts
packages/happy-dom/test/fetch/SyncFetch.test.ts
packages/integration-test/test/tests/Fetch.test.js
packages/jest-environment/test/javascript/JavaScript.test.ts

This adds the end boundary to the multipart/form-data as described in #1741

fix: [#1741] Add end boundary to FormData

---

packages/happy-dom/src/event/Event.ts

fix: [#1747] Event phases should be on both class and instance

---

packages/happy-dom/src/cookie/urilities/CookieURLUtility.ts
packages/happy-dom/test/cookie/CookieContainer.test.ts

fix: [#1162] Fix supporting secure flag for http localhost domains

---

packages/happy-dom/src/query-selector/SelectorItem.ts
packages/happy-dom/src/query-selector/SelectorParser.ts
packages/happy-dom/test/query-selector/QuerySelector.test.ts

feat: [#990] Add support for multiple selectors in :not pseudo-class

---

packages/happy-dom/src/nodes/node/NodeList.ts
packages/happy-dom/test/nodes/node/NodeList.test.ts

fix: [#1698] Handle invalid indeces on childNodes

---

packages/happy-dom/src/xml-http-request/XMLHttpRequest.ts
packages/happy-dom/test/xml-http-request/XMLHttpRequest.test.ts

Implement this web standard according to the specs.
https://xhr.spec.whatwg.org/#the-overridemimetype()-method

feat: [#1782] Add overrideMimeType to XMLHttpRequest
