capricorn86/happy-dom

- src/Window.ts
- test/dom-implementation/DOMImplementation.test.ts
This adds animation frame support adding `requestAnimationFrame` and `cancelAnimationFrame` functions to the window
ref #9
> feat(dom): add support for animation frames

- src/AsyncWindow.ts
I ran into a problem while trying to integrate this library into angular SSR. There are compile errors because Response object is taken from fetch namespace and not node fetch as DOM library needs to be available for typescript compilation. Changing this to explizit named imports avoids naming conflicts.
> Reduce possible namespace conflicts

- package-lock.json
- src/nodes/basic-types/node/Node.ts
- test/element/Element.test.ts
[`prepend`](https://developer.mozilla.org/en-US/docs/Web/API/ParentNode/prepend) and [`append`](https://developer.mozilla.org/en-US/docs/Web/API/ParentNode/append) API for adding multiple nodes and text nodes at once.
> Add support for prepend and append

- src/event/EventTarget.ts
- test/event/EventTarget.test.ts
event.target was always null, but I think it ought to be the EventTarget itself.
Rather than just assign target to the EventTarget on the event, I'm creating a new object using Object.create and assigning target to it.
I'm not sure what the spec says should be done in this case but it felt like modifying the passed argument was not the right thing to do.
If you'd rather I just change the incoming event let me know and I'll strip out the cloning logic (and test modifications for it).
> sets target on event when dispatched

- packages/jest-environment/README.md
As package was renamed, it has to be used differently with Jest.
> #0@trivial: Update jest-environment README

- packages/happy-dom/src/nodes/document/Document.ts
- packages/happy-dom/src/nodes/document/IDocument.ts
- packages/happy-dom/src/nodes/node/INode.ts
- packages/happy-dom/src/nodes/node/Node.ts
- packages/happy-dom/test/nodes/document/Document.test.ts
- packages/happy-dom/test/nodes/node/Node.test.ts
Hello. At first, thank you for your great work!
I noticed that the `Document` object does not have an `adoptNode` method, so I tried to add it. Also, there is an inconsistency in the `Node.removeChild` method - it should return the removed node.
- [Issue #244]
- [Issue #243 ]
> When I tried to compile the project I got a lot of TS errors. Thus I had no possibility to test it :( So I do not ask for a merging of the pull request, but a review.
> Adding support for `Document.adoptNode` method.

- packages/happy-dom/src/nodes/element/Element.ts
see https://github.com/vitest-dev/vitest/pull/234
Maybe it is also a problem on `lit` side.
closes #321
> #321@patch: `tagName` can be null.

- packages/happy-dom/src/nodes/document/Document.ts
- packages/happy-dom/test/nodes/document/Document.test.ts
Fixes https://github.com/capricorn86/happy-dom/issues/330
I used a getter instead of a static property for 3 reasons:
- we want to have the exact same object as `window.location` so that changes made in one will also impact the other (so I didn't use `new Location()`)
- the document has a view `this._defaultView` that can be updated, so `document.location` should always be up-to-date with the linked view
- it won't be overridable 
I also added a test that passes `npm test`
--- 
Note: this is my first PR to the project, so I'm not sure I followed every guideline
> #330@minor: Add document.location.

- packages/happy-dom/src/nodes/element/ClassList.ts
- packages/happy-dom/test/nodes/element/ClassList.test.ts
Fixes https://github.com/capricorn86/happy-dom/issues/328
Implements `toggle()` on `ClassList` (see https://developer.mozilla.org/en-US/docs/Web/API/DOMTokenList/toggle)
> #328@minor: Add toggle() to ClassList.

- packages/happy-dom/src/nodes/html-style-element/HTMLStyleElement.ts
Without this change every time one calls `styleElement.sheet` a new CSSStyleSheet is returned.
> fix: HTMLStyleElement should cache the created CSSStyleSheet

- packages/happy-dom/src/event/EventTarget.ts
I faced this issue while testing one of my functionality. 
Current code removes all the event listers. This becomes an issue if multiple event listeners are registered for the same type.
Keeping the [deleteCount](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/splice) as 1 removes one event listener at a time.
> @fix: remove one event callback at a time

- packages/happy-dom/src/config/ElementTag.ts
- packages/happy-dom/src/index.ts
- packages/happy-dom/src/nodes/html-meta-element/HTMLMetaElement.ts
- packages/happy-dom/src/nodes/html-meta-element/IHTMLMetaElement.ts
- packages/happy-dom/src/window/IWindow.ts
- packages/happy-dom/src/window/Window.ts
- packages/happy-dom/test/nodes/html-meta-element/HTMLMetaElement.test.ts
test code: 
```javascript
const happy = require("happy-dom")
const window = new happy.Window();
const  document = window.document;
document.write(`
<html>
<head>
<meta name="meta2" http-equiv="Content-Type" content="text/html; charset=utf-8">
</head>
</html>
`)
console.log(document.getElementsByTagName("meta")[0].httpEquiv);
console.log(document.getElementsByTagName("meta")[0].content);
console.log(document.getElementsByTagName("meta")[0].name);
```
before: 
```shell
undefined
undefined
undefined
```
after:
```shell
Content-Type
text/html; charset=utf-8
meta2
```
`npm test` pass:
> #369@minor: Adds support for HTMLMetaElement.

- packages/jest-environment/README.md
`node` is the new default environment since [Jest 27](https://jestjs.io/blog/2021/05/25/jest-27#flipping-defaults).
> Indicate new jest default environment in README

- packages/happy-dom/src/exception/DOMExceptionNameEnum.ts
- packages/happy-dom/src/window/Window.ts
- packages/happy-dom/src/window/WindowBase64.ts
- packages/happy-dom/test/window/Window.test.ts
> #499@minor: Adds support for btoa and atob.

- packages/happy-dom/src/nodes/html-element/DatasetUtility.ts
fixes #501 
Simplest solution was to add the toString method.
I did try to change types and write a wrapper function the proxy handler uses, but major blocking point of that was a type error I couldn't resolve. Mainly `type symbol can not be used as an index` which since version [4.4](https://github.com/Microsoft/TypeScript/issues/24587#issuecomment-890314169) of typescript is completely valid. Couldn't figure out why it wouldn't allow it in this specific repo, as I wasn't having issues with my other ones.
> #501@patch: allow proxy keys besides strings

- packages/happy-dom/src/query-selector/SelectorItem.ts
- packages/happy-dom/test/query-selector/QuerySelector.test.ts
Fixes #513 
The assumption that the code was making is that no additional selectors were appearing after a psuedo selector appears to be an incorrect one. As the selector that was mentioned failing in the issue is using the following `input:not([list])[type="search"]`.  
Replacing the psuedo selector instead, using the already available regex, seems to allow only checking against the base selector, but doesn't remove any additional selectors after the psuedo one(s).
> #513@patch: Selector item not factoring in selectors after a psuedo selector

- packages/happy-dom/src/config/ElementTag.ts
- packages/happy-dom/src/nodes/html-button-element/HTMLButtonElement.ts
- packages/happy-dom/src/nodes/html-button-element/IHTMLButtonElement.ts
- packages/happy-dom/test/nodes/html-button-element/HTMLButtonElement.test.ts
When writing some tests, I noticed this:
```
const el = document.createElement("button")
el.setAttribute("disabled", "")
console.log(el.disabled)  // <-- Prints "undefined"
```
In a real browser, the last line would print out `true`. Checked in Chrome and FireFox.
After digging a bit, I realized that `happy-dom` uses the generic `HTMLElement` to represent a `<button>`, which doesn't translate between [standard button attributes and properties](https://developer.mozilla.org/en-US/docs/Web/API/HTMLButtonElement).
This PR adds a `HTMLButtonElement` class and makes it translate some (not all) of the properties - specifically, `value`, `disabled`, and `type`.
> Add support for HTMLButtonElement.

- packages/happy-dom/src/index.ts
- packages/happy-dom/src/nodes/attr/Attr.ts
- packages/happy-dom/src/nodes/document/Document.ts
- packages/happy-dom/src/nodes/document/IDocument.ts
- packages/happy-dom/src/nodes/element/Element.ts
- packages/happy-dom/src/nodes/element/IElement.ts
- packages/happy-dom/src/nodes/node/INode.ts
- packages/happy-dom/src/nodes/node/Node.ts
- packages/happy-dom/src/nodes/node/NodeDocumentPositionEnum.ts
- packages/happy-dom/src/nodes/node/NodeUtility.ts
- packages/happy-dom/src/nodes/processing-instruction/IProcessingInstruction.ts
- packages/happy-dom/src/nodes/processing-instruction/ProcessingInstruction.ts
- packages/happy-dom/src/window/IWindow.ts
- packages/happy-dom/src/window/Window.ts
- packages/happy-dom/test/nodes/document/Document.test.ts
- packages/happy-dom/test/nodes/node/Node.test.ts
- packages/happy-dom/test/nodes/node/NodeUtility.test.ts
Resolves #524 
Hello there 👋🏻 
I've tried to implement `compareDocumentPosition` into the code base. I hope I've done the job correctly. Feel free to send me some feedback if needed 🙏🏻 I'll be happy to learn from you guys.
Notable changes:
- Added `nodeType` in `Attr` (of type `ATTRIBUTE_NODE`)
- Added `ProcessingInstruction` node & `IProcessingInstruction` interface
- Added `createProcessingInstruction` in `Document` (required to properly test `nodeEquals` method)
- Added `NodeDocumentPositionEnum` enum
References:
- https://dom.spec.whatwg.org/#dom-node-comparedocumentposition
- https://dom.spec.whatwg.org/#attr
- https://dom.spec.whatwg.org/#dom-node-attribute_node
- https://dom.spec.whatwg.org/#concept-node-equals
- https://dom.spec.whatwg.org/#processinginstruction
- …
> #524@minor: Add support for Node.compareDocumentPosition().

- packages/happy-dom/src/nodes/node/Node.ts
- packages/happy-dom/src/nodes/node/NodeList.ts
- packages/happy-dom/test/nodes/html-button-element/HTMLButtonElement.test.ts
- packages/happy-dom/test/nodes/html-dialog-element/HTMLDialogElement.test.ts
- packages/happy-dom/test/nodes/html-element/HTMLElement.test.ts
- packages/happy-dom/test/nodes/html-form-element/HTMLFormElement.test.ts
- packages/happy-dom/test/nodes/html-image-element/HTMLImageElement.test.ts
- packages/happy-dom/test/nodes/html-input-element/HTMLInputElement.test.ts
- packages/happy-dom/test/nodes/html-label-element/HTMLLabelElement.test.ts
- packages/happy-dom/test/nodes/html-link-element/HTMLLinkElement.test.ts
- packages/happy-dom/test/nodes/html-media-element/HTMLMediaElement.test.ts
- packages/happy-dom/test/nodes/html-meta-element/HTMLMetaElement.test.ts
- packages/happy-dom/test/nodes/html-opt-group-element/HTMLOptGroupElement.test.ts
- packages/happy-dom/test/nodes/html-option-element/HTMLOptionElement.test.ts
- packages/happy-dom/test/nodes/html-script-element/HTMLScriptElement.test.ts
- packages/happy-dom/test/nodes/html-select-element/HTMLSelectElement.test.ts
- packages/happy-dom/test/nodes/html-style-element/HTMLStyleElement.test.ts
- packages/happy-dom/test/nodes/html-template-element/HTMLTemplateElement.test.ts
- packages/happy-dom/test/nodes/html-text-area-element/HTMLTextAreaElement.test.ts
Hi, this PR fixes #540 by adding `Symbol.toStringTag` to `Node` and `NodeList` classes.
> #540@patch: Add toStringTag in Element class to handle Object.prototype.toString.call

- packages/global-registrator/src/GlobalRegistrator.ts
> #603@patch: Fixes problem in the "global-registrator" package  where unregister only deletes/pops half the registered keys

- packages/happy-dom/src/window/Window.ts
- packages/happy-dom/test/window/Window.test.ts
> #627@patch: Fix location.href initialization in Window.

- packages/happy-dom/src/css/declaration/AbstractCSSStyleDeclaration.ts
- packages/happy-dom/src/nodes/html-element/HTMLElement.ts
- packages/happy-dom/src/nodes/html-element/IHTMLElement.ts
- packages/happy-dom/test/css/declaration/CSSStyleDeclaration.test.ts
- packages/happy-dom/test/nodes/html-element/HTMLElement.test.ts
This PR adds a setter on `HTMLElement.style` the reproduce the behaviour of DOM implementations, as explained in #628. 
This also fixes another difference between happy-dom and browser implementations: setting `null` or `''` as `style` (or in `cssText`)  shouldn't remove the `style` attribute.
```ts
element.style.cssText = null;
console.log(element.getAttribute('style')); // displays '', not null
```
Since TypeScript forces a value returned by a getter to be assignable to a setter (see https://github.com/microsoft/TypeScript/pull/42425), the `style` setter accepts a `CSSStyleDeclaration` but then resets the `cssText`, as implemented in some browsers.
Closes #628
> #628@patch: Handle style setter in HTMLElement.

- packages/happy-dom/src/nodes/html-option-element/HTMLOptionElement.ts
- packages/happy-dom/test/nodes/html-option-element/HTMLOptionElement.test.ts
> #648@patch: OptionElement.value returns `textContent` as fallback.

- packages/happy-dom/src/window/IWindow.ts
- packages/happy-dom/src/window/Window.ts
- packages/happy-dom/test/window/Window.test.ts
Add [scrollX](https://developer.mozilla.org/en-US/docs/Web/API/Window/scrollX), [scrollY](https://developer.mozilla.org/en-US/docs/Web/API/Window/scrollY), [pageXOffset](https://developer.mozilla.org/en-US/docs/Web/API/Window/pageXOffset) and [pageYOffset](https://developer.mozilla.org/en-US/docs/Web/API/Window/pageYOffset)  to `Window`
> #681@minor: Add scrollX, scrollY, pageXOffset, pageYOffset to window.

- packages/happy-dom/src/css/CSSParser.ts
- packages/happy-dom/src/css/declaration/utilities/CSSStyleDeclarationElementStyle.ts
- packages/happy-dom/src/css/rules/CSSContainerRule.ts
- packages/happy-dom/src/css/rules/CSSMediaRule.ts
CSSContainerRule, CSSMediaRule has conditionText prop, not conditionalText
https://developer.mozilla.org/en-US/docs/Web/API/CSSConditionRule
> #692@patch: Fixed  CSSContainerRule, CSSMediaRule conditionText typo

- packages/happy-dom/src/nodes/node/Node.ts
- packages/happy-dom/src/nodes/node/NodeUtility.ts
- packages/happy-dom/test/nodes/node/NodeUtility.test.ts
Fixes #656.
Not sure if this is something you want to include. I'm just trying to help with this issue.
Here's the link to the spec: https://dom.spec.whatwg.org/#concept-node-equals
If you think I should change anything in the PR, let me know! I assigned the `minor` label, but I'll leave that to you to decide if it's correct. Cheers 🍻 !
> #656@minor: Rename `nodeEquals` to `isEqualNode`.

- packages/happy-dom/src/css/declaration/utilities/CSSStyleDeclarationElementStyle.ts
- packages/happy-dom/src/event/Event.ts
- packages/happy-dom/src/nodes/node/Node.ts
- packages/happy-dom/test/event/Event.test.ts
Fixes #709.
Not exactly sure about this `instanceof ShadowRoot` check with an extra import as I couldn't find other similar usages the codebase. Will be happy to update this PR If there's a more desirable pattern.
> #709@patch: Properly detect `ShadowRoot` boundary when constructing `composedPath`

- .github/workflows/pull_request.yml
- .github/workflows/release.yml
- .gitignore
- package-lock.json
- package.json
- turbo.json
Hi, we have been reviewing your project and we find it very interesting. Seeing that you used lerna to manage the monorepo, we thought that by migrating it to turborepo you could gain a bit of agility both locally and running on github actions. If you start using turborepo, you can cache both local and ci-cd executions and and run the scripts in parallel. There are some more advantages like using npm to manage the workspace and not that lerna has to do it.
We leave you some benchmarks for you to compare and see if you find it interesting.
Executions on github actions:
First Execution: 1m 55s (average)
Second execution with turborepo cache: 29s (average)
If you want to investigate a little more, here you have the documentation and any questions we are here to help you. …
> Migrate lerna to turborepo

- packages/happy-dom/src/event/Event.ts
- packages/happy-dom/test/event/Event.test.ts
- packages/happy-dom/test/nodes/html-element/HTMLElement.test.ts
- turbo.json
Fix #722 by implementing `timeStamp` property on `Event`.
According to specification (see [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Event/timeStamp) and [Spec](https://dom.spec.whatwg.org/#ref-for-dom-event-timestamp%E2%91%A0)) the `timeStamp` property is described as follows:
> _This value is the number of milliseconds elapsed from the beginning of the time origin until the event was created. If the global object is [Window](https://developer.mozilla.org/en-US/docs/Web/API/Window), the time origin is the moment the user clicked on the link, or the script that initiated the loading of the document. In a worker, the time origin is the moment of creation of the worker._
My proposed solution is to use `performance.timeOrigin` as the time origin to resolve the relative Event …
> #722@minor: Add timeStamp property to Event.

- packages/happy-dom/src/event/EventTarget.ts
- packages/happy-dom/src/event/IEventListenerOptions.ts
- packages/happy-dom/src/nodes/document/Document.ts
- packages/happy-dom/test/event/EventTarget.test.ts
> #700@minor: Add event listener options.

- packages/happy-dom/src/nodes/html-input-element/HTMLInputElement.ts
> #729@patch: Convert input value to string.

- packages/happy-dom/src/nodes/html-element/HTMLElement.ts
- packages/happy-dom/test/nodes/html-element/HTMLElement.test.ts
Fixes #771.
Only updated existing `HTMLElement` tests that expect `bubbles` value of `blur/focus` events to be `false` from now.
Actual event bubbling is still covered by `Node.test.ts`.
> #771@patch: Don't bubble `focus` and `blur` events through DOM.

- packages/happy-dom/src/nodes/document/Document.ts
- packages/happy-dom/src/nodes/document/IDocument.ts
- packages/happy-dom/src/nodes/document/VisibilityStateEnum.ts
> #774@patch: Add visibility state to Document.

- packages/happy-dom/src/xml-parser/XMLParser.ts
- packages/happy-dom/test/xml-parser/XMLParser.test.ts
Fix #519
e.g.
```javascript
const window = new Window(), document = window.document;
const html = `<html>
</html>`;
document.write(html);
const source = new window.XMLSerializer().serializeToString(document);
console.assert(source === html);
console.log(window.location);
// Location {
// 	href: 'about:blank',
// 		origin: 'null',
// 		protocol: 'about:',
// 		username: '',
// 		password: '',
// 		host: '',
// 		hostname: '',
// 		port: '',
// 		pathname: 'blank',
// 		search: '',
// 		searchParams: URLSearchParams {},
// 	hash: ''
// }
```
> #519@patch: Fixes XMLParser Bug.

- packages/happy-dom/package.json
- packages/happy-dom/src/xml-http-request/XMLHttpRequest.ts
- packages/happy-dom/src/xml-http-request/utilities/XMLHttpRequestSyncRequestScriptBuilder.ts
Fix #783 
**Warn**: Import dependency: [`iconv-lite`](https://www.npmjs.com/package/iconv-lite)
NEED TEST UNIT!
> #783@patch: Fixes XMLHttpRequest response encoding error.

- packages/happy-dom/src/nodes/document/Document.ts
- packages/happy-dom/src/nodes/document/IDocument.ts
- packages/happy-dom/test/nodes/document/Document.test.ts
> #785@minor: Add document.title.

- packages/happy-dom/src/nodes/html-audio-element/Audio.ts
- packages/happy-dom/src/window/Window.ts
> #778@minor: Add Audio class to window.

- packages/global-registrator/tsconfig.json
- packages/happy-dom/tsconfig.json
- packages/jest-environment/tsconfig.json
this will build and include declaration maps alongside the declarations, allowing "go to definition" to lead to the source instead of a definition file. To see just the types "go to type definition" will still work.
> #842@trivial: Adds declaration maps.

- packages/happy-dom/src/index.ts
- packages/happy-dom/src/nodes/document/Document.ts
- packages/happy-dom/src/nodes/document/IDocument.ts
- packages/happy-dom/src/tree-walker/INodeFilter.ts
- packages/happy-dom/src/tree-walker/NodeIterator.ts
- packages/happy-dom/src/tree-walker/TreeWalker.ts
- packages/happy-dom/src/window/IWindow.ts
- packages/happy-dom/src/window/Window.ts
- packages/happy-dom/test/nodes/document/Document.test.ts
- packages/happy-dom/test/tree-walker/NodeIterator.test.ts
fix #297
- Create class `NodeIterator` (uses `TreeWalker` internally to forward "nextNode" and "previosNode").
- Add `NodeIterator` to global scope.
- Add method `Document.createNodeIterator`.
- Add plain function type to `INodeFilter`.
- Add unit tests for method and class (dumb copy&paste from TreeWalker tests).
> #297@minor: Add method Document.createNodeIterator.

- packages/happy-dom/src/nodes/text/Text.ts
- packages/happy-dom/test/nodes/text/Text.test.ts
fix #857 and unit tests for `Text.splittext`:
- the DOMException needs to be actually thrown
- missing check for negative index
- added unit test
> #857@patch: Throw DOMException from Text.splitText.

- packages/happy-dom/src/css/CSSParser.ts
- packages/happy-dom/test/css/CSSParser.test.ts
- packages/happy-dom/test/css/data/CSSParserInput.ts
Fix CSS regex so comment content is a non-greedy "any character or whitespace" instead of the previous "anything but *".
> #887@patch: Fix parsing CSS comments with asterisks.

- packages/happy-dom/src/nodes/html-anchor-element/HTMLAnchorElement.ts
- packages/happy-dom/test/nodes/html-anchor-element/HTMLAnchorElement.test.ts
Fixes `toString()` of `HTMLAnchorElement` as described in #890
> #890@patch: Fixes a issue where "HTMLAnchorElement.toString" returns outerHTML instead of the url

- packages/happy-dom/src/nodes/html-input-element/HTMLInputDateUtility.ts
- packages/happy-dom/src/nodes/html-input-element/HTMLInputElement.ts
- packages/happy-dom/src/nodes/html-input-element/HTMLInputElementValueSanitizer.ts
- packages/happy-dom/test/nodes/html-input-element/HTMLInputElement.test.ts
- packages/happy-dom/test/nodes/html-input-element/HTMLInputElementValueSanitizer.test.ts
- Enhance HTMLInputElementValueSanitizer to be more compliant with specs at https://html.spec.whatwg.org/multipage/input.html (breaking change)
- Change HTMLInputElement get valueAsNumber to be more compliant with specs at https://html.spec.whatwg.org/multipage/input.html (breaking change)
- Add support for HTMLInputElement set valueAsNumber based on specs at https://html.spec.whatwg.org/multipage/input.html
This is come as a replacement of PR#946
> #945@minor Add support for HTMLInputElement set valueAsNumber

- packages/happy-dom/src/nodes/html-label-element/HTMLLabelElement.ts
- packages/happy-dom/test/nodes/html-label-element/HTMLLabelElement.test.ts
This supports nested / descendent input elements for HTMLLabelElement's `control` property and also supports other labelable elements, as described in the spec:
https://html.spec.whatwg.org/multipage/forms.html#category-label
To be fully spec-compliant, the `control` getter would ignore `for` element(s) that aren't labelable elements, and labelable elements would also include form-associated custom elements.
I'm using a CSS selector for this, because that seemed like the most convenient approach, but if another approach would be better (e.g., for performance?), please let me know.
Fixes #530.
> #530@minor: Broader support for HTMLLabelElement `control`.

- packages/happy-dom/src/nodes/element/Element.ts
- packages/happy-dom/src/nodes/element/IElement.ts
- packages/happy-dom/test/nodes/element/Element.test.ts
Very naive implementation of https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollHeight
To be able to test https://mui.com/material-ui/react-textarea-autosize/ without warnings:
```
Warning: `NaN` is an invalid value for the `height` css style property.
at textarea
at TextareaAutosize (node_modules/@mui/base/node/TextareaAutosize/TextareaAutosize.js:41:7)
at node_modules/@emotion/react/dist/emotion-element-b63ca7c6.cjs.dev.js:43:23
at div
at node_modules/@emotion/react/dist/emotion-element-b63ca7c6.cjs.dev.js:43:23
at InputBase (node_modules/@mui/material/node/InputBase/InputBase.js:224:44)
at OutlinedInput (node_modules/@mui/material/node/OutlinedInput/OutlinedInput.js:129:44)
at div
[...]
```
> Add naive scrollHeight implementation

- package-lock.json
- package.json
- packages/global-registrator/package.json
- packages/global-registrator/test/tsconfig.json
- packages/happy-dom/package.json
- packages/happy-dom/src/console/VirtualConsole.ts
- packages/happy-dom/src/window/IWindow.ts
- packages/happy-dom/src/window/Window.ts
- packages/happy-dom/test/window/Window.test.ts
- packages/integration-test/package.json
- packages/jest-environment/package.json
- packages/uncaught-exception-observer/package.json
- packages/uncaught-exception-observer/test/UncaughtExceptionObserver.test.ts
Fixes https://github.com/capricorn86/happy-dom/issues/1050
- Update `@types/node`
- The v15 was listed but the v16 is used in the CI (by the way, the v16 is OEL, see [Node versions support](https://github.com/nodejs/release#release-schedule), so it should be updated to v18 or to the v20, and same for the types)
- Node v15 supports webcrypto but the types for Node v15 don't include it
- Update import for `ConsoleConstructor` (not available anymore on the global `NodeJS` object, but has to be imported from `node:console`)
- Define as `window.crypto = require('crypto').webcrypto`
> Add window.crypto

- packages/happy-dom/src/event/EventTarget.ts
- packages/happy-dom/src/event/IEventTarget.ts
- packages/happy-dom/src/fetch/AbortSignal.ts
- packages/happy-dom/test/event/EventTarget.test.ts
- packages/happy-dom/test/fetch/AbortSignal.test.ts
> #1097@patch: Implements Symbol.toStringTag on EventTarget and AbortSignal.

- packages/happy-dom/src/nodes/document/Document.ts
- packages/happy-dom/src/nodes/document/IDocument.ts
- packages/happy-dom/src/nodes/element/Element.ts
- packages/happy-dom/src/nodes/html-script-element/HTMLScriptElement.ts
- packages/happy-dom/src/nodes/html-script-element/HTMLScriptElementUtility.ts
- packages/happy-dom/test/nodes/document/Document.test.ts
- packages/happy-dom/test/nodes/html-script-element/HTMLScriptElement.test.ts
> #1099@minor: Add support for currentScript.

- packages/happy-dom/src/mutation-observer/MutationListener.ts
- packages/happy-dom/src/mutation-observer/MutationObserver.ts
- packages/happy-dom/src/nodes/character-data/CharacterData.ts
- packages/happy-dom/src/nodes/element/ElementNamedNodeMap.ts
- packages/happy-dom/src/nodes/node/NodeUtility.ts
- packages/happy-dom/test/mutation-observer/MutationObserver.test.ts
> #1113@patch: Fixes second parameter missing from MutationObserver callback.

- packages/global-registrator/src/GlobalRegistrator.ts
I'm far from an expert in this area, but it seems to do the trick. Inspired by the approach used by vitest to populate the globals: https://github.com/vitest-dev/vitest/blob/ffaf16b489cdaa39ef5cafba11a3f8139c184d35/packages/vitest/src/integrations/env/utils.ts#L44.
No test because tests are already broken on Node 18, and this will fix them (for this package).
Fixes #1140
> #1140@patch: Fix Node 18.18.2+ support in global-registrator.

- .github/workflows/pull_request.yml
- packages/happy-dom/src/nodes/html-input-element/HTMLInputElementDateUtility.ts
- packages/happy-dom/test/nodes/html-input-element/HTMLInputElement.test.ts
- packages/happy-dom/test/nodes/html-input-element/HTMLInputElementDateUtility.test.ts
- packages/happy-dom/test/window/Window.test.ts
- packages/uncaught-exception-observer/test/UncaughtExceptionObserver.test.ts
Also fixed tests that were failing locally for me, for various reasons.
Closes #1144
> #1144@patch: Run tests against newer Node.js versions

- packages/happy-dom/src/event/EventTarget.ts
- packages/happy-dom/test/event/EventTarget.test.ts
This might fix #1182 and fixes usage with `bun test`.
> fix: [#1182] The handleEvent method should be called with the listener scope

- packages/happy-dom/src/nodes/html-option-element/HTMLOptionElement.ts
- packages/happy-dom/test/nodes/html-option-element/HTMLOptionElement.test.ts
This might fix "Wrong select value when option with empty value is selected #1138 ".
> fix: [#1138] Modify option node to return empty string even if the value is empty string

- packages/happy-dom/src/css/declaration/element-style/CSSStyleDeclarationElementStyle.ts
- packages/happy-dom/test/window/BrowserWindow.test.ts
Fix: https://github.com/capricorn86/happy-dom/issues/1308
The previous code was incorrect in its use of [RegExp.prototype.exec](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/exec), and the regular expression matching was performed only once.
`RegExp.prototype.exec` is difficult to use correctly because it is a stateful API.
I modified the logic using [String.prototype.matchAll](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/matchAll) as described in MDN.
> In addition, [String.prototype.matchAll()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/matchAll) helps to simplify matching multiple parts of a string (with capture groups) by allowing you to iterate over the …
> fix: [#1308] Fix a bug of multiple fallbacks of custom property

- packages/happy-dom/src/dom-token-list/DOMTokenList.ts
- packages/happy-dom/test/dom-token-list/DOMTokenList.test.ts
Fixes: https://github.com/capricorn86/happy-dom/issues/1342
> fix: [#1342] Make `DOMTokenList` iterable

- packages/happy-dom/src/fetch/Request.ts
- packages/happy-dom/src/fetch/Response.ts
- packages/happy-dom/test/fetch/Request.test.ts
- packages/happy-dom/test/fetch/Response.test.ts
Currently `Request.formData` only handles "multipart/form-data", but it seems that it should also support "application/x-www-form-urlencoded" according to the specs. https://fetch.spec.whatwg.org/#dom-body-formdata
Current behavior:
```typescript
const params = new URLSearchParams();
params.append("d", "data");
const req = new Request("https://example.com", { method: "POST", body: params });
for (const [key, value] of req.headers.entries()) {
console.log(`${key}: ${value.split(";")[0]}`);
}
// content-type: application/x-www-form-urlencoded
(async () => {
for (const [key, value] of (await req.formData()).entries()) {
console.log(`${key}: ${value}`);
}
// DOMException [InvalidStateError]: Failed to build FormData object: The "content-type" header isn't of type "multipart/form-data".
})(); …
```
> feat: Adds support for application/x-www-form-urlencoded in Request.formData

- packages/happy-dom/src/css/declaration/element-style/CSSStyleDeclarationElementStyle.ts
- packages/happy-dom/test/window/BrowserWindow.test.ts
Close #1363 
Custom properties without fallback values can be converted to custom properties with fallback values (using `SINGLE_CSS_VARIABLE_REGEXP`).
e.g.
- `var(--known)`
- In this case, you can resolve the value of the custom property by examining the value of `--known`.
- `var(--unknown, var(--known)` 
- This case can be converted to a custom property with a fallback value of the form `var(--unknown, known-color)` by resolving the `--known` value.
- `var(--unknown, var(--unknown, var(--known)))`
- This case can also be converted to a custom property with a fallback value of the form `var(--unknown, var(--unknown, known-color))` by resolving the value of `--known`.
After converting to a custom property for which a fallback value exists, the value can be found using a regular …
> fix: [#1363] Fix bug with missing fallback value

- packages/happy-dom/src/nodes/document/Document.ts
- packages/happy-dom/test/nodes/document/Document.test.ts
Close #1380
Run in Chrome:
Run in Safari:
Run in Firefox:
> Fix a bug in createTextNode when the data argument is a non-string

- packages/jest-environment/test/angular/Angular.test.ts
Previously, the `describe` block in `Angular.test.ts` was named `React`. This PR names it to `Angular`.
Addresses [this Issue](https://github.com/capricorn86/happy-dom/issues/1394)
> fix: [#1394] Update angular jest environment describe to say Angular

- packages/happy-dom/src/browser/types/IGoToOptions.ts
- packages/happy-dom/src/browser/utilities/BrowserFrameNavigator.ts
- packages/happy-dom/src/nodes/html-iframe-element/HTMLIFrameElementNamedNodeMap.ts
- packages/happy-dom/src/nodes/html-iframe-element/HTMLIFrameElementPageLoader.ts
- packages/happy-dom/test/nodes/html-iframe-element/HTMLIFrameElement.test.ts
Implement the iframe srcdoc attribute, which should operate similarly to the src attribute but with higher priority, without the need to initiate a fetch request.
Also, I have fixed several bugs: 
+ When remove the src or srcdoc attributes, the iframe should be reloaded.
+ For non-cross-domain iframes, after being connected to the Document, their contentWindow’s parent/top properties should not be null.
References:
+ [W3C-the-iframe-element.html#attr-iframe-src](https://www.w3.org/TR/2010/WD-html5-20100624/the-iframe-element.html#attr-iframe-src)
> feat: [#1398] Add support for iframe srcdoc

- packages/happy-dom/src/index.ts
- packages/happy-dom/src/nodes/element/DOMRect.ts
- packages/happy-dom/src/nodes/element/DOMRectReadOnly.ts
- packages/happy-dom/src/window/BrowserWindow.ts
- packages/happy-dom/test/nodes/element/DOMRect.test.ts
- packages/happy-dom/test/nodes/element/DOMRectReadOnly.test.ts
Resolves https://github.com/capricorn86/happy-dom/issues/1161
Implements `DOMReact` and `DOMReactReadOnly` classes according to spec https://drafts.fxtf.org/geometry/#DOMRect
> fix: [#1161] Implement DOMReact and DOMReactReadOnly interfaces

- packages/happy-dom/src/nodes/document/Document.ts
- packages/happy-dom/test/nodes/document/Document.test.ts
Return `document.forms` as `HTMLCollection` instead of `NodeList`.
https://developer.mozilla.org/en-US/docs/Web/API/Document/forms
Related to #1349.
> fix: [#1349] Return forms as html collection

- packages/happy-dom/src/nodes/element/ElementUtility.ts
- packages/happy-dom/test/nodes/element/Element.test.ts
Resolves #1406.
I found that when the reference node is not an Element, such as a comment, the insertion correctly occurs in the `childNodes` array, but the target node is not removed from `childNodes`; it is only removed from `children`. Therefore, I have added code that also removes the target node from `childNodes`.
> fix: [1406] Fixes issue with insertBefore and comment reference node

- packages/happy-dom/src/nodes/document/Document.ts
- packages/happy-dom/test/nodes/document/Document.test.ts
> feat: [#1411] Add queryCommandSupported method.

- packages/happy-dom/src/nodes/document/Document.ts
- packages/happy-dom/test/nodes/document/Document.test.ts
Provide mock implementation of `document.elementFromPoint`
> fix: [#1400] Implement document.elementFromPoint

- packages/happy-dom/src/storage/StorageFactory.ts
- packages/happy-dom/test/storage/Storage.test.ts
This fixes #1418.
`L79-84` checks that if a property does not exist in proxy target it return `undefined` for the configuration of the property and `Object.keys(window.sessionStorage, '<existent_property_key>')` returns `{ configurable: true, /** truncated for brevity */ }` on the browser (_Tested on MS Edge 124_). 
https://github.com/capricorn86/happy-dom/blob/c29f36c5644eacd0546b5c302ecd6bd7feacf50f/packages/happy-dom/src/storage/StorageFactory.ts#L78-L92
1. Fix `Object.{entries,keys,values}()` throwing `TypeError` on `Storage` by setting `{ configurable: true }` for all existent property in the `Storage`
1. Add tests for above changes
> fix: [#1418] Fix Object.{entries,key,values} on Storage

- packages/happy-dom/src/nodes/html-anchor-element/HTMLAnchorElement.ts
- packages/jest-environment/test/react/React.test.tsx
> fix: [#1464] Fix react click handler with `preventDefault` on anchor not preventing navigation

- packages/happy-dom/src/nodes/element/ElementUtility.ts
- packages/happy-dom/test/nodes/element/Element.test.ts
After recent changes the Element.insertBefore is not behaving as in the browser.
When a node is inserted into a element that already contains it, it does nothing.
Fixes https://github.com/capricorn86/happy-dom/issues/1429
Browser behavior:
> fix: [#1429] Element.insertBefore works when the node is already inserted

- packages/happy-dom/src/file/Blob.ts
- packages/happy-dom/test/file/Blob.test.ts
https://developer.mozilla.org/en-US/docs/Web/API/Blob/stream
Some libraries, like zip.js, use this method internally. Therefore it is impossible right now to test code that uses such libraries.
> feat: Support Blob.stream().

- packages/happy-dom/src/nodes/html-select-element/HTMLSelectElement.ts
- packages/happy-dom/test/nodes/html-select-element/HTMLSelectElement.test.ts
This resolves #1526 and adds a couple of tests to ensure no regression can happen.
I took the main fix here from `HTMLFormElement`: https://github.com/capricorn86/happy-dom/blob/20b520aa40d811dfd297b63fd66276d371b85b90/packages/happy-dom/src/nodes/html-form-element/HTMLFormElement.ts#L99
Let me know if any changes are needed.
> fix: [#1526] handle missing symbol props in HTMLSelectElement 

- packages/happy-dom/src/nodes/child-node/ChildNodeUtility.ts
- packages/happy-dom/src/nodes/element/Element.ts
- packages/happy-dom/src/nodes/parent-node/ParentNodeUtility.ts
- packages/happy-dom/test/nodes/child-node/ChildNodeUtility.test.ts
- packages/happy-dom/test/nodes/element/Element.test.ts
- packages/happy-dom/test/nodes/parent-node/ParentNodeUtility.test.ts
- packages/happy-dom/tsconfig.json
Happy-DOM's current handling of inserting items into the DOM that are not nodes via `.prepend()`, `.append()`, `.before()`, `.after()`, `.replaceWith()` or `.replaceChildren()` is incorrect and might even allow for XSS vulnerabilities:
If an item is a string, Happy-DOM parses the string as HTML and inserts the parsed HTML. However, the actual behavior should be to add text nodes with the string as the text content, which is then automatically sanitized.
```js
element.append("<script>");
console.log(element.innerHTML);
// Expected result: "&lt;script&gt;"
// Actual result: "<script></script>"
```
Additionally, if an item is neither a string nor a node, the browser converts it to a string automatically, but Happy-DOM errors.
```js
element.append(123, true, {}); …
```
> Fix incorrect handling of non-node items inserted into the DOM

- packages/happy-dom/src/nodes/html-input-element/HTMLInputElement.ts
- packages/happy-dom/test/nodes/html-input-element/HTMLInputElement.test.ts
> fix: [#1604] Consider null as empty string when setting it as value in HTMLInputElement.value

- packages/happy-dom/src/cookie/urilities/CookieStringUtility.ts
- packages/happy-dom/src/css/utilities/CSSParser.ts
- packages/happy-dom/src/nodes/html-hyperlink-element/HTMLHyperlinkElementUtility.ts
- packages/happy-dom/src/query-selector/SelectorItem.ts
- packages/happy-dom/src/query-selector/SelectorParser.ts
If you want to determine the first character only, it is more efficient to use `===` directly. [example](https://perf.link/#eyJpZCI6InVqYjN3Z21wOXNxIiwidGl0bGUiOiJGaW5kaW5nIG51bWJlcnMgaW4gYW4gYXJyYXkgb2YgMTAwMCIsImJlZm9yZSI6ImNvbnN0IGRhdGEgPSBbLi4uQXJyYXkoMTAwMCkua2V5cygpXS5tYXAoKCkgPT4gTWF0aC5yYW5kb20oKS50b1N0cmluZygxNikuc2xpY2UoMikpIiwidGVzdHMiOlt7Im5hbWUiOiJzdGFydHNXaXRoIiwiY29kZSI6ImRhdGEuZm9yRWFjaChzdHIgPT4gc3RyLnN0YXJ0c1dpdGgoc3RyKSkiLCJydW5zIjpbMzAwMCwyODAwMCwyOTAwMCwxNjAwMCw0MDAwLDE1MDAwLDEwMDAwLDE1MDAwLDIxMDAwLDQyMDAwLDQwMDAsNDcwMDAsMzkwMDAsNDcwMDAsMTAwMDAsMzYwMDAsNDYwMDAsNDQwMDAsNDAwMDAsMTAwMCwyMDAwMCwzNTAwMCw0OTAwMCw0MjAwMCwzMDAwLDQ1MDAwLDM2MDAwLDQ2MDAwLDIwMDAsMTAwMCw5MDAwLDIwMDAsMzUwMDAsNDMwMDAsMzAwMCw0MDAwLDYwMDAsMTEwMDAsNDAwMCwzNzAwMCw0NjAwMCwyMDAwLDYwMDAsNDAwMCw5MDAwLDkwMDAs …
> perf: [#1609] Replace `startsWith` with the equal sign

- packages/happy-dom/src/browser/utilities/BrowserFrameURL.ts
- packages/happy-dom/src/history/History.ts
Allow for an URL to be a string or an URL object in History.pushState() and History.replaceState() APIs. 
Solves [1621](https://github.com/capricorn86/happy-dom/issues/1621)
> fix: [#1621] Allow for an URL to be a string or an URL object in History.pushState() and History.replaceState() APIs

- packages/happy-dom/src/query-selector/QuerySelector.ts
- packages/happy-dom/test/query-selector/QuerySelector.test.ts
Remove a type check which is covered by (and shadows) subsequent checks.
> fix: Remove redundant querySelector type check

- packages/happy-dom/src/query-selector/QuerySelector.ts
- packages/happy-dom/src/query-selector/SelectorCombinatorEnum.ts
- packages/happy-dom/src/query-selector/SelectorParser.ts
- packages/happy-dom/test/query-selector/QuerySelector.test.ts
> feat: [#1683] Adds support for subsequent sibling combinator to query selectors and match

- packages/happy-dom/test/fetch/Fetch.test.ts
I'll start off with some examples before fully committing as there a lot of tests. If you're happy with these changes feel free to merge this and I'll continue with the refactor. By the way, perhaps you should allow for refactor type in commit message.
> feat: [1502] Reduce duplication in tests

- packages/happy-dom/src/nodes/html-table-section-element/HTMLTableSectionElement.ts
- packages/happy-dom/test/nodes/html-table-element/HTMLTableElement.test.ts
- packages/happy-dom/test/nodes/html-table-section-element/HTMLTableSectionElement.test.ts
Adds support for implementing the insertRow and deleteRow methods on the HtmlTableSectionElement to match the browser implementation. Fixes #1708
> feat: [1708] Add support for insertRow and deleteRow to HTMLTableSectionElement

- packages/happy-dom/src/query-selector/QuerySelector.ts
- packages/happy-dom/test/query-selector/QuerySelector.test.ts
Found and fixed a minor bug where we still aren't quite returning the same result in querySelect() and querySelectAll()[0] when there are grouped selectors. The fix was to pass through the updated document position to recursive calls, which was missed during #1713.
Fixes #1720
> fix: [1720] Fix bug where nested query selector is not returning the correct result when there are multiple matching selectorGroups

- packages/happy-dom/src/browser/DefaultBrowserSettings.ts
- packages/happy-dom/src/browser/types/IBrowserSettings.ts
- packages/happy-dom/src/browser/types/IOptionalBrowserSettings.ts
- packages/happy-dom/src/match-media/MediaQueryItem.ts
- packages/happy-dom/test/match-media/MediaQueryList.test.ts
As mentioned in #1724, this is an implementation we're using locally via `pnpm patch` and it's been working well. I modeled the change after work done previously in #354, so hopefully I'm not too off base. I did consider making the `prefersReducedMotion` setting a boolean, but I think it makes more sense to accept the valid string values for the setting, which is also more future proof if they ever decide to extend the spec to accept more values.
Thanks for all the work on this project!
> feat: [#1724] Add prefers-reduced-motion support

- packages/happy-dom/src/PropertySymbol.ts
- packages/happy-dom/src/browser/utilities/BrowserFrameNavigator.ts
- packages/happy-dom/src/fetch/AbortController.ts
- packages/happy-dom/src/fetch/AbortSignal.ts
- packages/happy-dom/src/fetch/Fetch.ts
- packages/happy-dom/src/fetch/SyncFetch.ts
- packages/happy-dom/test/browser/BrowserFrame.test.ts
- packages/happy-dom/test/browser/detached-browser/DetachedBrowserFrame.test.ts
- packages/happy-dom/test/fetch/AbortSignal.test.ts
- packages/happy-dom/test/fetch/Fetch.test.ts
- packages/happy-dom/test/fetch/SyncFetch.test.ts
> fix: [#1718] AbortSignal reason can have any type and the value should be used without being wrapped when rejecting a fetch

- packages/jest-environment/bin/copy-tsdef-for-lit.cjs
The node api replaces the cp command, which is not compatible with Windows.
> refactor: Node API replaces cp command

- packages/happy-dom/src/nodes/html-element/HTMLElementUtility.ts
- packages/happy-dom/test/nodes/html-input-element/HTMLInputElement.test.ts
> fix: [#1563] Prevent disabled inputs from being focussed or blurred

- packages/happy-dom/src/window/BrowserWindow.ts
Without this, I get a TimeoutNaNWarning: NaN is not a number. (with bun)
It doesn't seem a bad thing to actually set the timer to 0 for all anyway, but it might very well be something that bun needs to fix
> fix: [#1772] Set 0 instead of undefined as default in setTimeout to prevent Bun from logging a "TimeoutNaNWarning"

- README.md
- packages/happy-dom/README.md
Fix for https://github.com/capricorn86/happy-dom/issues/1795
> chore: [#1795] Replace old Angular domain angular.io with angular.dev

- packages/happy-dom/src/nodes/html-anchor-element/HTMLAnchorElement.ts
- packages/happy-dom/test/nodes/html-anchor-element/HTMLAnchorElement.test.ts
From the spec anchor tags should handle bubbling events.
https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-a-element
This is also the behaviour of Chrome and Firefox.
> fix: [#1775] Anchor tag handles bubbling clicks

- packages/happy-dom/src/file/File.ts
The File constructor was incorrectly replacing slashes (/) in the filename with colons (:), resulting in names like "foo:bar.jpg" instead of the expected "foo/bar.jpg".
This commit updates the behavior to align with browser implementations:
- Slashes in the provided filename are preserved.
Reference: 
https://github.com/jsdom/jsdom/commit/2ab99ad18d58585e4958aca0911ed142fac80b71
https://developer.mozilla.org/en-US/docs/Web/API/File/File#filename
> fix [#1788]: preserve slashes in filename and match browser behavior

- packages/happy-dom/src/fetch/Request.ts
- packages/happy-dom/test/fetch/Request.test.ts
* Allow empty request URL string, e.g. when running `window.fetch("")`.
* Fixes #1779
> fix: [#1779] Allow empty URL string in Request

- packages/happy-dom/src/nodes/html-form-element/HTMLFormElement.ts
- packages/happy-dom/test/nodes/html-form-element/HTMLFormElement.test.ts
Aligns with the [HTML spec](https://html.spec.whatwg.org/#constructing-form-data-set) ("4. Let entry list be a new empty entry list.") and observed behaviour in browsers. Previously the existing query string would be appended to.
> fix: Overwrite existing URL query string on form submit when method is "GET"

- packages/happy-dom/src/nodes/node/Node.ts
- packages/happy-dom/test/mutation-observer/MutationObserver.test.ts
Fixes: https://github.com/capricorn86/happy-dom/issues/1803
The test content is consistent with browser behavior:
> ![image](https://github.com/user-attachments/assets/fbe5718f-3094-45aa-b2cd-2407cb0284b6)
> fix: [#1803] Fixes issue where the sibling obtained when MutationObserver monitors node removal was null
